name: Generate-images-automatically

on:
  schedule:
    - cron: '0 12 * * *'
  workflow_dispatch: null

jobs:
  create-profile:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: aquaproj/aqua-installer@11dd79b4e498d471a9385aa9fb7f62bb5f52a73c # v4.0.4
        with:
          aqua_version: v2.56.6
      - run: deno task generate --out _site/profile.svg
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
      - uses: actions/configure-pages@983d7736d9b0ae728b81ab479565c72886d7745b # v5.0.0
      - uses: actions/upload-pages-artifact@7b1f4a764d45c48632c6b24a0339c27f5614fb0b # v4.0.0
        with:
          path: _site
      - uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e # v4.0.5
        id: deploy
  create-lapras-card:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs:
      - create-profile
    steps:
      - uses: kawamataryo/lapras-card-readme@97beea07675cba3eded93eaeb71744413d7f8e8b # v1.3.0
        with:
          SHARE_ID: K4AJVET
          ICON_FIRST: "#888888"
          ICON_SECOND: "#cccccc"
          BACKGROUND_FIRST: "#767676"
          BACKGROUND_SECOND: "#e1e1e1"
          LANG: "en"
          UPDATE_TIME: "false"
