name: deno basic ci

on:
  - push

jobs:
  deno_fmt:
    timeout-minutes: 30
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - uses: denoland/setup-deno@084daf99a803bfd9caf63c2e3c151960decf2755 # v1.5.0
      - run: deno task fmt:check
  deno_check:
    timeout-minutes: 30
    permissions:
      contents: read
    runs-on: ubuntu-latest
    needs: deno_fmt
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - uses: denoland/setup-deno@084daf99a803bfd9caf63c2e3c151960decf2755 # v1.5.0
      - run: deno task check
  deno_lint:
    timeout-minutes: 30
    permissions:
      contents: read
    runs-on: ubuntu-latest
    needs: deno_fmt
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - uses: denoland/setup-deno@084daf99a803bfd9caf63c2e3c151960decf2755 # v1.5.0
      - run: deno task lint
