name: LAPRAS Card

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  update-card:
    timeout-minutes: 30
    name: LAPRAS Card
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: kawamataryo/lapras-card-readme@97beea07675cba3eded93eaeb71744413d7f8e8b # v1.3.0
        with:
          SHARE_ID: K4AJVET
          ICON_FIRST: "#888888"
          ICON_SECOND: "#cccccc"
          BACKGROUND_FIRST: "#767676"
          BACKGROUND_SECOND: "#e1e1e1"
          LANG: "en"
          UPDATE_TIME: "false"
