name: GitHub-Profile-Summary-Cards

on:
  schedule: # execute every 24 hours
    - cron: '* */24 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate

    steps:
      - uses: actions/checkout@v3
      - uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          USERNAME: ${{ github.repository_owner }}
      - name: Generate metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.TOKEN }}
          user: Omochice
      - name: Generate language activity
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.TOKEN }}
          filename: metrics.plugin.languages.svg
          base: ""
          plugin_languages: yes
          plugin_languages_indepth: yes
          commits_authoring: firstname lastname, username, username@users.noreply.github.com
          plugin_languages_sections: recently-used
          plugin_languages_recent_load: 400
          plugin_languages_recent_days: 14
      - name: Detailed display
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.achievements.svg
          token: ${{ secrets.TOKEN }}
          base: ""
          plugin_achievements: yes
          plugin_achievements_only: sponsor, maintainer, octonaut
